# Need a nerd font for additional icons (e.g. FiraCode Nerd Font)
# https://www.nerdfonts.com/font-downloads

format = """
$time\
$character\
$username\
[î‚°](bg:cyan fg:pink)\
$directory\
[î‚°](fg:cyan bg:orange)\
$git_branch\
$git_status\
[î‚°](fg:orange bg:yellow)\
$deno\
$nodejs\
$python\
$ruby\
[î‚° ](fg:yellow)\
"""

# Use the Dracula color palette
# https://github.com/dracula/starship
palette = "dracula"

[palettes.dracula]
background = "#282a36"
current_line = "#44475a"
foreground = "#f8f8f2"
comment = "#6272a4"
cyan = "#8be9fd"
cyan_fg = "#003f5c"
green = "#50fa7b"
green_fg = "#004d40"
orange = "#ffb86c"
orange_fg = "#5f4120"
pink = "#ff79c6"
pink_fg = "#6d0f3f"
purple = "#bd93f9"
purple_fg = "#46237a"
red = "#ff5555"
red_fg = "#8b0000"
yellow = "#f1fa8c"
yellow_fg = "#715b17"


[time]
disabled = false
time_format = "%R" # Hour:Minute Format
format = '[î‚¶](purple)[ğŸ”® $time ](bg:purple fg:purple_fg)'

[username]
show_always = true
format = '[ ğŸ‘¸ ](bg:pink fg:pink_fg)'
disabled = false

[directory]
format = "[ ğŸ° $path ](bg:cyan fg:cyan_fg)"
truncation_length = 0
truncate_to_repo = true

[git_branch]
symbol = "ï˜"
format = '[ $symbol $branch ](bg:orange fg:orange_fg)'

[git_status]
conflicted = 'ğŸ³ '
ahead = 'ğŸ‘†'
behind = 'ğŸ‘‡'
diverged = 'ğŸ’€ '
up_to_date = 'ğŸŒ·'
untracked = 'ğŸ€ '
stashed = ''
modified = 'âš”ï¸ '
staged = 'ğŸ’… '
renamed = 'âš¡ï¸ '
deleted = 'ğŸ’¥ '
format = '[$all_status$ahead_behind ](bg:orange)'

[deno]
symbol = "ğŸ¦•"
format = '[ $symbol ($version) ](bg:yellow fg:yellow_fg)'

[nodejs]
symbol = "ğŸµ"
format = '[ $symbol ($version) ](bg:yellow fg:yellow_fg)'

[python]
symbol = "ğŸ"
format = '[ $symbol ($version) ](bg:yellow fg:yellow_fg)'

[ruby]
symbol = "ğŸ’"
format = '[ $symbol ($version) ](bg:yellow fg:yellow_fg)'

[character]
success_symbol = '[î‚°](bg:pink fg:purple)'
error_symbol = '[î‚°](bg:red purple)[ ğŸ‘¹ ](red bg:red)[î‚°](red bg:pink)'
format = '$symbol'
