[tools]
node = "latest"
python = "latest"
ruby = "3.4"
deno = "latest"
"npm:@devcontainers/cli" = "0.80.1"
"npm:@sentry/cli" = "latest"

[settings]
idiomatic_version_file_enable_tools = ["node", "python", "ruby", "java"]
experimental = true
